### ISSUE TITLE
Could linearmodels handle stream data?

### ISSUE THREAD

**Issue by Echo-Ji** [bashtage/linearmodels#162]
When I use PanelOLS do regression like:

`mod = PanelOLS(data[depv], data[indv])`

I get the error about insufficient memory.

Then I would like to use `Spark` to handle the problem.

But I do not know whether linearmodels could handle stream data.

**Comment by bashtage** [comment]
Sorry, so support for anything like streaming.  That would need a substantially different approach than the one used to update particular matrices.

**Comment by Echo-Ji** [comment]
Sorry I have no idea about the approach you mentioned. Could you please explain it?

And the error I encountered is:

```
Traceback (most recent call last):
  File "all_data.py", line 79, in <module>
loading data...
MultiIndex and set X, Y...
OLS...
    mod = PanelOLS(data[depv], data[indv])
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/linearmodels/panel/model.py", line 748, in __init__
    super(PanelOLS, self).__init__(dependent, exog, weights=weights)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/linearmodels/panel/model.py", line 168, in __init__
    self.exog = PanelData(exog, 'Exog')
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/linearmodels/panel/data.py", line 200, in __init__
    self._frame = self._frame.astype(np.float64, copy=False)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/util/_decorators.py", line 178, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/core/generic.py", line 5001, in astype
    **kwargs)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/core/internals.py", line 3714, in astype
    return self.apply('astype', dtype=dtype, **kwargs)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/core/internals.py", line 3581, in apply
    applied = getattr(b, f)(**kwargs)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/core/internals.py", line 575, in astype
    **kwargs)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/core/internals.py", line 664, in _astype
    values = astype_nansafe(values.ravel(), dtype, copy=True)
  File "/usr/local/python3.5.2/lib/python3.5/site-packages/pandas/core/dtypes/cast.py", line 730, in astype_nansafe
    return arr.astype(dtype, copy=True)
MemoryError
```
I will appreciate it if you could give me some insights about how to solve it.

**Comment by bashtage** [comment]
MemoryError indicates that your arrays are too large for the system you are attempting to estimate the model on. linearmodels is in-memory only

**Comment by Echo-Ji** [comment]
That is fine. Thanks for your patience,
